import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Link from 'next/link'
import Header from '../components/Header'
import Billboard from '../components/Billboard'
import billboardListings from '../public/listings'
import { useSession, signIn, signOut } from "next-auth/react"

export default function Account() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Billboard/>

    {/* preview of your content. welcome (name) at the top
    two sections split into billboards you are currently purchasing and billboards you own and are trying to 
    rent out     */}

      <div>
        <p>
            test paragraph
        </p>
      </div>
    </div>
  )
}
