import Head from 'next/head'
<<<<<<< HEAD
import Image from 'next/image'
import React from 'react'
import Link from 'next/link'
import Header from '../components/Header'
import Billboard from '../components/Billboard'
import billboardListings from '../public/listings'
import { useSession, signIn, signOut } from "next-auth/react"

export default function Account() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Billboard/>

    {/* preview of your content. welcome (name) at the top
    two sections split into billboards you are currently purchasing and billboards you own and are trying to 
    rent out     */}

      <div>
        <p>
            test paragraph
        </p>
      </div>
    </div>
  )
}
=======
import React from 'react'
import Header from '../components/Header/Header'
import { useSession, useSupabaseClient, useUser } from '@supabase/auth-helpers-react'
import Account from '../components/Account'

export default function MyAccount() {

  const session = useSession()
  if(session != undefined)
    return (
        <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header/>

        <Account session={session} />
        
        </div>
    )
  else
  return (
    <div>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header/>

    <div>404 Error</div>
    
    </div>
  )
}
>>>>>>> main
