import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useContext } from 'react'
// import styles from '../styles/Home.module.css'
// import { createUserWithEmailAndPassword, getAuth } from '../config/firebase'

export default function CreateAccount() {
  const [form, setForm] = useState({
    email: '',
    password: ''
  });
  
  // let signUp = ({name, email, password}) => {
  //   return createUserWithEmailAndPassword(getAuth(), form.email, form.password)
  //     .then((userCredentials) => {
  //       console.log(userCredentials)
  //     })
  //     .catch((error) => {
  //       console.log(error);
  //     })
  // }

  // const onSubmitHandler = (data) => {
    // return signUp(data).then((user) => {
    //   console.log(user)
    // })
  // }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2> Create an account </h2> 
        <form>
          <input type="text" placeholder="Email Address" autoComplete="username" value={form.email} onChange={e => setForm({...form, email: e.target.value})} required></input> <br></br>
          <input type="password" placeholder="Enter Password" autoComplete="new-password" value={form.password} onChange={e => setForm({...form, password: e.target.value})} required></input> <br></br>
          <button type="submit">Submit</button>
        </form>
      </main>
    </div>
  )
}
