import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function CreateAccount() {
  const [form, setForm] = useState({
    email: '',
    password: ''
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2> Create an account </h2> 
        <form>
          <input type="text" placeholder="Email Address" value={form.email} onChange={e => setForm({...form, email: e.target.value})} required></input> <br></br>
          <input type="password" placeholder="Enter Password" value={form.password} onChange={e => setForm({...form, password: e.target.value})} required></input> <br></br>
          <button type="submit">Submit</button>
        </form>
      </main>
    </div>
  )
}
