import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Link from 'next/link'
import Header from '../components/header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      Electronic Billboard Management System
      <button value="login">Login</button>
      <button value="signup" >
        <Link href="/create">
          Sign Up
        </Link>
      </button>
    </div>
  )
}
