import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Link from 'next/link'
import Header from '../components/Header'
import Billboard from '../components/Billboard'
import billboardListings from '../public/listings'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <div style={{width: "800px"}}>
        {React.Children.toArray(billboardListings.map((props) => {
          return <Billboard {...props}/>
        }))}
      </div>

      {/* Electronic Billboard Management System
      <button value="login">Login</button>
      <button value="signup" >
        <Link href="/create">
          Sign Up
        </Link>
      </button> */}
      
    </div>
  )
}
