
import React, { useState, useEffect } from 'react'
import styles from '../components/Search.module.css'
// import { createUserWithEmailAndPassword, getAuth } from '../config/firebase'

function Search () {
  const [, setFetchError] = useState(null)
  const [data, setLocation] = useState(null)

  useEffect(() => {
    const fetchLocation = async () => {
      const {data, error} = await supabase
        .from('ad_bookings')
        .select('name')
        .contains('name', ['value']) // 'value' will be whatever is entered in the search bar

    }  
  })
  // let signUp = ({name, email, password}) => {
  //   return createUserWithEmailAndPassword(getAuth(), form.email, form.password)
  //     .then((userCredentials) => {
  //       console.log(userCredentials)
  //     })
  //     .catch((error) => {
  //       console.log(error);
  //     })
  // }

  // const onSubmitHandler = (data) => {
    // return signUp(data).then((user) => {
    //   console.log(user)
    // })
  // }

  return (
    <div>
      <Head>
        <title>Welcome to the Search Bar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2> BillBoards </h2> 
        <form>
          <input type="text" placeholder="BillBoard Search" autoComplete="Name" value={form.email} onChange={e => setForm({...form, data: e.target.value})} required></input> <br></br>
          <button type="submit">Submit</button>
        </form>
        <h3> TV </h3> 
        <form>
          <input type="text" placeholder="Email Address" autoComplete="username" value={form.email} onChange={e => setForm({...form, data: e.target.value})} required></input> <br></br>
          <button type="submit">Submit</button>
        </form>
      </main>
    </div>
  )
}
export default Search;
