import Head from 'next/head'
import React from 'react'
import Billboard from '../components/Billboard'
import billboardListings from '../public/listings'

export default function Test() {
  return (
    <div style={{width: "475px", backgroundColor:"#FFFFFF"}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {React.Children.toArray(billboardListings.map((props) => {
          return <Billboard {...props}/>
        }))}
    </div>
  )
}
